/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package bookshopparthenope;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.stage.Stage;


public class App extends Application {

    public static void main(String[] args) {


        launch();
    }



    @Override
    public void start(Stage primaryStage) throws Exception {
        FXMLLoader fxmlLoader = new FXMLLoader(LoginController.class.getResource("/bookshopparthenope/gui/login.fxml"));
        Scene scene = new Scene(fxmlLoader.load(), 650, 450);
        primaryStage.setTitle("Book Shop Parthenope");
        primaryStage.setScene(scene);
        primaryStage.show();
        primaryStage.setResizable(false);
        Image icon = new Image("bookshopparthenope/gui/images/logoDesktop.png");
        primaryStage.getIcons().add(icon);

    }
    /*
    @Override
    public void start(Stage stage) throws IOException {
        try {
            FXMLLoader loader = new FXMLLoader(getClass().getClassLoader().getResource("../../resources/GUI/login.fxml"));
            Parent root = FXMLLoader.load(LoginController.class.getResource("../../resources/GUI/login.fxml"));
            Scene scene = new Scene(root);
            String css = this.getClass().getResource("javacss.css").toExternalForm();
            scene.getStylesheets().add(css);
            Image icon = new Image("gui/images/logoapp.png");
            stage.getIcons().add(icon);
            stage.setTitle("Book Shop Parthenope");
            stage.setScene(scene);
            stage.setResizable(false);
            stage.show();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }*/
}
