/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package bookshopparthenope;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.stage.Stage;


public class App extends Application {

    public static void main(String[] args) {


        launch();
    }



    @Override
    public void start(Stage primaryStage) throws Exception {
        FXMLLoader fxmlLoader = new FXMLLoader(LoginController.class.getResource("/bookshopparthenope/gui/login.fxml"));
        Scene scene = new Scene(fxmlLoader.load(), 650, 450);
        primaryStage.setTitle("Book Shop Parthenope");
        primaryStage.setScene(scene);
        primaryStage.show();
        primaryStage.setResizable(false);
        Image icon = new Image("bookshopparthenope/gui/images/logoDesktop.png");
        primaryStage.getIcons().add(icon);

    }

}
